cities = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
    "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
    "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte",
    "San Francisco", "Indianapolis", "Seattle", "Denver", "Boston",
    "Nashville", "Detroit", "El Paso", "Memphis", "Portland",
    "Oklahoma City", "Las Vegas", "Louisville", "Baltimore", "Milwaukee",
    "Albuquerque", "Tucson", "Fresno", "Sacramento", "Mesa",
    "Kansas City", "Atlanta", "Long Beach", "Colorado Springs", "Raleigh",
    "Miami", "Virginia Beach", "Omaha", "Oakland", "Minneapolis",
    "Tulsa", "Arlington", "Tampa", "New Orleans", "Wichita",
    "Cleveland", "Bakersfield", "Aurora", "Anaheim", "Honolulu",
    "Santa Ana", "Corpus Christi", "Riverside", "Lexington", "Stockton",
    "Toledo", "St. Paul", "Newark", "Greensboro", "Plano",
    "Henderson", "Lincoln", "Buffalo", "Jersey City", "Chula Vista",
    "Fort Wayne", "Orlando", "St. Petersburg", "Chandler", "Laredo",
    "Norfolk", "Durham", "Madison", "Lubbock", "Irvine",
    "Winston-Salem", "Glendale", "Garland", "Hialeah", "Reno",
    "Chesapeake", "Gilbert", "Baton Rouge", "Irving", "Scottsdale",
    "North Las Vegas", "Fremont", "Boise", "Richmond", "San Bernardino"
]

animals = [
    "Bald Eagles", "Blue Whales", "Komodo Dragons", "Monarch Butterflys",
    "Snow Leopards", "Giant Pandas", "Emperor Penguins", "Green Sea Turtles",
    "Honey Bees", "Red Foxs", "African Elephants", "Grizzly Bears",
    "Orangutans", "Arctic Wolfs", "Coral Snakes", "Octopuss",
    "Tyrannosaurus Rexs", "Dodo Birds", "Woolly Mammoths", "Great White Sharks",
    "Bull Sharks", "Whales", "Dolphins", "Seals", "Otters",
    "Penguins", "Albatrosses", "Falcons", "Owls", "Eagles",
    "Vultures", "Crows", "Parrots", "Hummingbirds", "Woodpeckers",
    "Snakes", "Lizards", "Geckos", "Chameleons", "Crocodiles",
    "Alligators", "Turtles", "Tortoises", "Frogs", "Toads",
    "Salamanders", "Newts", "Bees", "Wasps", "Ants",
    "Butterflies", "Moths", "Beetles", "Dragonflies", "Fireflies",
    "Spiders", "Scorpions", "Crabs", "Lobsters", "Shrimp",
    "Squids", "Cuttlefish", "Jellyfish", "Starfish", "Sea Urchins",
    "Corals", "Sponges", "Lions", "Tigers", "Leopards",
    "Cheetahs", "Jaguars", "Bears", "Wolves", "Foxes",
    "Deer", "Elk", "Moose", "Bison", "Buffaloes",
    "Rhinos", "Hippos", "Giraffes", "Zebras", "Gazelles",
    "Kangaroos", "Koalas", "Wombats", "Platypuses", "Echidnas",
    "Monkeys", "Apes", "Gorillas", "Chimpanzees", "Orangutans",
    "Lemurs", "Sloths", "Armadillos", "Pangolins", "Aardvarks",
    "Triceratops", "Stegosaurus", "Brachiosaurus", "Velociraptors", "Pterodactyls",
    "Sabertooth Cats", "Mammoths", "Mastodons", "Giant Ground Sloths", "Dodos"
]
